CREATE TABLE produtos (
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    ID_PRODUTO NUMBER(9) CONSTRAINT pk_produto PRIMARY KEY,
    DATA_INSERCAO DATE NOT NULL,
    DATA_VALIDADE DATE,
    FORNECEDOR_PRODUTO VARCHAR(100) NOT NULL
);

SELECT * FROM produtos;